# Generated by Django 6.0.3 on 2026-03-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postnom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
