# Generated by Django 6.0.3 on 2026-04-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_user_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='code_postal',
        ),
    ]
