# Generated by Django 6.0.3 on 2026-04-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_remove_adresse_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.province'),
        ),
    ]
