# Generated by Django 6.0.3 on 2026-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_adresse_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricdata',
            name='biometric_completed',
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_completed',
            field=models.BooleanField(default=False),
        ),
    ]
