# Generated by Django 6.0.3 on 2026-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_remove_biometricdata_biometric_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
