# Generated by Django 6.0.3 on 2026-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_user_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'Masculin'), ('FEMININ', 'Féminin'), ('AUTRE', 'Autre')], max_length=15),
        ),
    ]
