# Generated by Django 6.0.3 on 2026-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_user_date_naissance_alter_user_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
