# Generated by Django 6.0.3 on 2026-03-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CNI', "Carte d'identité"), ('PAS', 'Passeport'), ('PER', 'Permis de conduire'), ('ACT', 'Acte de naissance'), ('DOM', 'Justificatif de domicile')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rejet', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
